### ISSUE TITLE
Type error when using AlignmentFlag instead of Alignment

### ISSUE THREAD

**Issue by bpabel** [python-qt-tools/PySide2-stubs#2]
The following code inaccurately reports a type error:

```python
from PySide2.QtWidgets import QLineEdit
from PySide2.QtCore import Qt

line = QLineEdit()
line.setAlignment(Qt.AlignRight)

```

PyLance reports the following error

```
Argument of type "AlignmentFlag" cannot be assigned to parameter "flag" of type "Alignment" in function "setAlignment"
  "AlignmentFlag" is incompatible with "Alignment"
Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

The error can be avoided by explicitly casting to an `Alignment()` (like if you combined flags with `Qt.AlignLeft | Qt.AlignTop`)

```
line.setAlignment(Qt.Alignment(Qt.AlignRight))
```

But `AlignmentFlags` objects should also be valid arguments to `setAlignment()`

**Comment by bluebird75** [comment]
Hi,

Thanks for the report. You are correct. Can you submit a PR ?

I did a huge work on PyQt5-stubs to fix precisely this. I lack the motivation to do it right now on PySide2-stubs but maybe it is really needed.

**Comment by bluebird75** [comment]
This has now been fixed in https://github.com/python-qt-tools/PySide2-stubs/commit/94f424c6a1df08634ac74fc60ee34e6e34ac9db9

Thanks for the report.
